name: Python application (Windows Build)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest
    env:
      APP_NAME: "fast-mic-toggle"
      PYTHON_VERSION: "3.14"
      ICON_PATH: "app/src/icon.ico"
      RELEASE_NAME: "Release v0.0.0"
      DEPENDENCIES: "pyaudiodevice"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        run: |
          pyinstaller app/main.py --onefile --name "${{ env.APP_NAME }}" --icon "${{ env.ICON_PATH }}" --collect-all "${{ env.DEPENDENCIES }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          tag_name: v0.0.0
          name: ${{ env.RELEASE_NAME }}
          draft: true
          files: dist/${{ env.APP_NAME }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
